# coding: utf-8

"""
    Onionoo

    Onionoo

    OpenAPI spec version: 4.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import onionoo
from onionoo.rest import ApiException
from onionoo.models.relay_summary_object import RelaySummaryObject


class TestRelaySummaryObject(unittest.TestCase):
    """ RelaySummaryObject unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRelaySummaryObject(self):
        """
        Test RelaySummaryObject
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = onionoo.models.relay_summary_object.RelaySummaryObject()
        pass


if __name__ == '__main__':
    unittest.main()
