# coding: utf-8

"""
    Onionoo

    Onionoo

    OpenAPI spec version: 4.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import onionoo
from onionoo.rest import ApiException
from onionoo.models.bridge_summary_object import BridgeSummaryObject


class TestBridgeSummaryObject(unittest.TestCase):
    """ BridgeSummaryObject unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBridgeSummaryObject(self):
        """
        Test BridgeSummaryObject
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = onionoo.models.bridge_summary_object.BridgeSummaryObject()
        pass


if __name__ == '__main__':
    unittest.main()
