# coding: utf-8

"""
    Onionoo

    Onionoo

    OpenAPI spec version: 4.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import onionoo
from onionoo.rest import ApiException
from onionoo.apis.documents_api import DocumentsApi


class TestDocumentsApi(unittest.TestCase):
    """ DocumentsApi unit test stubs """

    def setUp(self):
        self.api = onionoo.apis.documents_api.DocumentsApi()

    def tearDown(self):
        pass

    def test_get_summary(self):
        """
        Test case for get_summary

        Fetch a summary document
        """
        pass


if __name__ == '__main__':
    unittest.main()
