# coding: utf-8

"""
    Onionoo

    Onionoo

    OpenAPI spec version: 4.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RelaySummaryObject(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'f': 'str',
        'a': 'list[str]',
        'r': 'bool',
        'n': 'str'
    }

    attribute_map = {
        'f': 'f',
        'a': 'a',
        'r': 'r',
        'n': 'n'
    }

    def __init__(self, f=None, a=None, r=None, n=None):
        """
        RelaySummaryObject - a model defined in Swagger
        """

        self._f = None
        self._a = None
        self._r = None
        self._n = None

        self.f = f
        self.a = a
        self.r = r
        if n is not None:
          self.n = n

    @property
    def f(self):
        """
        Gets the f of this RelaySummaryObject.

        :return: The f of this RelaySummaryObject.
        :rtype: str
        """
        return self._f

    @f.setter
    def f(self, f):
        """
        Sets the f of this RelaySummaryObject.

        :param f: The f of this RelaySummaryObject.
        :type: str
        """
        if f is None:
            raise ValueError("Invalid value for `f`, must not be `None`")

        self._f = f

    @property
    def a(self):
        """
        Gets the a of this RelaySummaryObject.

        :return: The a of this RelaySummaryObject.
        :rtype: list[str]
        """
        return self._a

    @a.setter
    def a(self, a):
        """
        Sets the a of this RelaySummaryObject.

        :param a: The a of this RelaySummaryObject.
        :type: list[str]
        """
        if a is None:
            raise ValueError("Invalid value for `a`, must not be `None`")

        self._a = a

    @property
    def r(self):
        """
        Gets the r of this RelaySummaryObject.

        :return: The r of this RelaySummaryObject.
        :rtype: bool
        """
        return self._r

    @r.setter
    def r(self, r):
        """
        Sets the r of this RelaySummaryObject.

        :param r: The r of this RelaySummaryObject.
        :type: bool
        """
        if r is None:
            raise ValueError("Invalid value for `r`, must not be `None`")

        self._r = r

    @property
    def n(self):
        """
        Gets the n of this RelaySummaryObject.

        :return: The n of this RelaySummaryObject.
        :rtype: str
        """
        return self._n

    @n.setter
    def n(self, n):
        """
        Sets the n of this RelaySummaryObject.

        :param n: The n of this RelaySummaryObject.
        :type: str
        """

        self._n = n

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RelaySummaryObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
